version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
    - "devcyclehq/engineering"
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
    - "devcyclehq/engineering"
