name: Run Test Harness
on:
  pull_request:
    branches: [main]

jobs:
  harness-tests:
    name: Harness Tests
    runs-on:
      labels: ubuntu-latest-4-core
    steps:
      - uses: DevCycleHQ/test-harness@main
        with:
          sdks-to-test: dotnet
          sdk-github-sha: ${{github.event.pull_request.head.sha}}
          sdk-capabilities: '["cloud", "local","edgeDB", "clientCustomData","v2Config", "allFeatures", "allVariables", "evalReason"]'
