name: Run Test Harness
on:
  pull_request:
    branches: [main]
    paths:
      - DevCycle.SDK.Server.Cloud/**
      - DevCycle.SDK.Server.Local/**
      - DevCycle.SDK.Server.Common/**
      - .github/**

jobs:
  harness-tests:
    name: Harness Tests
    runs-on: ubuntu-latest
    steps:
      - uses: DevCycleHQ/test-harness@main
        with:
          sdks-to-test: dotnet
          sdk-github-sha: ${{ env.GITHUB_SHA }}
          github-token: ${{ secrets.TEST_HARNESS_GH_SECRET }}

