name: Test Run Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Using the DevCycle Internal Default key
  DVC_SERVER_SDK_KEY: "${{ secrets.EXAMPLE_DEVCYCLE_SERVER_SDK_KEY }}"

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.X
      - name: Restore dependencies
        run: |
          dotnet restore
      - name: Build
        run: |
          dotnet build --no-restore
      - name: Run Local Example
        run: |
          dotnet run --no-build --verbosity normal --project .\DevCycle.SDK.Server.Local.Example\DevCycle.SDK.Server.Local.Example.csproj
      - name: Run Cloud Example
        run: |
          dotnet run --no-build --verbosity normal --project .\DevCycle.SDK.Server.Cloud.Example\DevCycle.SDK.Server.Cloud.Example.csproj
          
          