name: Test Run Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Using the DevCycle Internal Default key
  DVC_SERVER_SDK_KEY: "${{ secrets.EXAMPLE_DEVCYCLE_SERVER_SDK_KEY }}"

jobs:
  run-example:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Common - Restore Packages
        run: |
          cd DevCycle.SDK.Server.Common
          nuget restore DevCycle.SDK.Server.Common.csproj

      - name: Common - Build
        run: |
          cd DevCycle.SDK.Server.Common
          msbuild.exe DevCycle.SDK.Server.Common.csproj /p:configuration="Release"

      - name: Local - Restore Packages
        run: |
          cd DevCycle.SDK.Server.Local
          nuget restore DevCycle.SDK.Server.Local.csproj

      - name: Local - Build
        run: |
          cd DevCycle.SDK.Server.Local
          msbuild.exe DevCycle.SDK.Server.Local.csproj /p:configuration="Release"

      - name: Example - Restore Packages
        run: |
          cd DevCycle.SDK.Server.Local.Example
          nuget restore DevCycle.SDK.Server.Local.Example.csproj

      - name: Example - Build
        run: |
          cd DevCycle.SDK.Server.Local.Example
          msbuild.exe DevCycle.SDK.Server.Local.Example.csproj /p:configuration="Release"
